@startuml
User -> LruCache: set(key, value)
LruCache -> HashMap :get(key)
LruCache <-- HashMap :return None
LruCache -> Node :Node(value)
LruCache <-- Node :new node
LruCache -> Node :set_key(key)
LruCache -> HashMap :put(key, node)
LruCache <-- HashMap :return True
LruCache -> DoubleLinkedList :insert_node_at_front(node)
LruCache <-- DoubleLinkedList :return True
User <-- LruCache: return True
@enduml